#!/bin/bash
set -eu
PARAMETERS="--progress --update --ignore-existing --links --ignore-errors"

SOURCES=/etc/backup/cloud.txt
EXCLUDE="-exclude=/home/milne/.config/Docker* --exclude=/home/milne/.config/libvirt/storage/autostart/gnome-boxes.xml"



# Backup .config	
DOTFILES='/home/milne/.config'
rclone sync $DOTFILES drive:Config $PARAMETERS --exclude=google-chrome/** --exclude=Code/** --exclude=Docker\ Desktop/**

# Backup rest
while read line || [ -n "$line" ];
do
	echo "Backing up $line to drive:"
	rclone sync $PARAMETERS $line drive:$line
#done < <(grep "" $SOURCES)
done < $SOURCES



#rclone sync $DOTFILES drive: $PARAMETERS '--exclude=google-chrome/* --exclude=Code/* --exclude=Docker\ Desktop/**'

