#!/bin/bash

SOURCES="$HOME/.config/MyDirectoriesToBackup.txt"
DESTINATION=$(cat "$HOME/.config/MyBackupDrive.txt")


## Backup ##	
while IFS= read -r line;
do
	echo "Backing up $line to $DESTINATION$line..."
	rsync "$line" "$DESTINATION" \
						--delete \
						--archive \
						--human-readable \
						--copy-links \
						--progress
done < "$SOURCES"



#rsync --copy-links --delete --archive --human-readable --progress \--exclude='Docker Desktop/Singleton*' --exclude='google-chrome/Singleton*' --exclude='libvirt/storage/autostart/gnome-boxes.xml'  /home/milne/.config/ /media/milne/Backup/.config/
